# 这个指的是 docker-compose 的版本? 待确定.
version: "3.5"
services:
  # nginx 的配置路径可以查看 https://github.com/nginxinc/docker-nginx/blob/dbd053d52727bc8db0fec704caa22b8e0d5f6c84/mainline/alpine/Dockerfile
  nginx:
    # 同时设置了 build 和 image, build 后以 image 的定义命名. 例如这个示例, image 的名称是 qiuyuhome/nginx:1.13.9-alpine
    build:
      # 指定 build 的路径.
      context: ./dockerfile.d/nginx
      # args:
      #  version: ${NGINX_VERSION}
    image: ${IMAGE_PREFIX}/nginx:${NGINX_VERSION}
    # 暴露容器端口到主机的任意端口或指定端口, 其他容器和主机都可以使用这个端口.
    ports:
      # 0.0.0.0是任意ip
      - ${NGINX_PORT}:80
    # labels 的作用是为了方便刷选容器. docker ps -f labels=com.qiuyuhome.lnmp, 详见我发起的问题: https://github.com/khs1994-docker/lnmp/issues/282
    labels:
      - ${LABEL_PRIFIX}.nginx=true
      - ${LABEL_PRIFIX}.lnmp=true
    # 数据卷所挂载路径设置, 可以设置宿主机路径（HOST:CONTAINER）或加上访问模式（HOST:CONTAINER:ro）,由（:）分隔的三个字段组成，<卷名>:<容器路径>:<选项列表>。选项列表，如：ro只读
    volumes:
      # 注意权限问题. 这个权限, 指的是容器中对挂在的路径所拥有的权限. 例如下面的只读的例子, 在容器中, 在/etc/nginx/conf.d下创建文件是没有权限的, 因为没有写入的权限.
      # 容器中的路径, 如果没有这个路径, 会自动创建, 如第一个例子, 会自动创建/app
      - ./app:/app:rw
      - ./config/nginx:/etc/nginx:rw
      - ./logs/nginx:/var/log/nginx:rw
    # 与 docker run -w 的效果一样. 指定当前的工作目录. 简单来说就是启动容器之后, 容器的当前目录就会是设置的这个目录. 经测试, 会自动创建这个目录
    working_dir: /app
    # 指定一个自定义容器名称, 而不是生成的默认名称, 由于Docker容器名称必须是唯一的，因此如果您指定了自定义名称，则无法将服务扩展到1个容器之外.
    container_name: lnmp-nginx
    # 与 docker run --restart 的效果一样. 可以设置三个值. no(默认值):容器退出时不重启, on-failure: 容器故障退出（返回值非零）时重启, always: 容器退出时总是重启
    restart: always
    # 网络
    networks:
      - backend
    # 传递给容器的环境变量, 注意, 这里是key, value, 用等号连接.
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - php7
  php7:
    build:
      context: ./dockerfile.d/php
    image: ${IMAGE_PREFIX}/php:${PHP_VERSION}
    volumes:
      - ./app:/app:rw
      - ./config/php:/usr/local/etc:rw
      - ./logs/php/php-fpm:/var/log/php:rw
    networks:
      - frontend
      - backend
    expose:
      - "9000"
    command: php-fpm -R -F
    environment:
      - TZ=Asia/Shanghai
    labels:
      - ${LABEL_PRIFIX}.php=true
      - ${LABEL_PRIFIX}.lnmp=true
    depends_on:
      - mysql
  mysql:
    build:
      context: ./dockerfile.d/mysql
    image: ${IMAGE_PREFIX}/mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql:rw
      - ./logs/mysql:/var/log/mysql:rw
    command:
      - mysqld
      - --character-set-server=utf8mb4
    labels:
      - ${LABEL_PRIFIX}.mysql=true
      - ${LABEL_PRIFIX}.lnmp=true
    networks:
      - frontend
      - backend
  phpmyadmin:
    build:
      context: ./dockerfile.d/phpmyadmin
    image: ${IMAGE_PREFIX}/phpmyadmin:${PHPMYADMIN_VERSION}
    environment:
      - PMA_HOST=mysql
    ports:
      - ${PHPMYADMIN_PORT}:80
    volumes:
      - /sessions
    labels:
      - ${LABEL_PRIFIX}.phpmyadmin=true
      - ${LABEL_PRIFIX}.lnmp=true
    depends_on:
      - mysql
    networks:
      - frontend
      - backend

  redis:
    build:
      context: ./dockerfile.d/redis
    image: ${IMAGE_PREFIX}/redis:${REDIS_VERSION}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./config/redis/redis.conf:/redis.conf:ro
      - ./logs/redis:/var/log/redis:rw
    command: [
      "redis-server",
      "/redis.conf",
      "--daemonize no",
      "--logfile /var/log/redis/redis.log",
      "--bind 0.0.0.0"
      ]
    labels:
      - ${LABEL_PRIFIX}.redis=true
      - ${LABEL_PRIFIX}.lnmp=true

networks:
    backend:
    frontend:

